/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grantmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Gregory Mitchell Completed the home page on 16/11/2024
 */
public class HomePage extends javax.swing.JFrame {//start class

    /**
     * Creates new form Home
     */
    public HomePage() {//home page constrcutor
        initComponents();
    }//end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        ShoaibLogoLabel = new javax.swing.JLabel();
        KarawanLogoLabel = new javax.swing.JLabel();
        GregLogoLabel = new javax.swing.JLabel();
        KarawanNameLabel = new javax.swing.JLabel();
        WelcomeIconLabel = new javax.swing.JLabel();
        GregNameLabel = new javax.swing.JLabel();
        ShoaibNameLabel = new javax.swing.JLabel();
        ShoaibSectionLabel1 = new javax.swing.JLabel();
        KarawanSectionLabel1 = new javax.swing.JLabel();
        KarawanSectionLabel2 = new javax.swing.JLabel();
        ShoaibSectionLabel2 = new javax.swing.JLabel();
        ShoaibSectionLabel3 = new javax.swing.JLabel();
        GregSectionLabel2 = new javax.swing.JLabel();
        GregSectionLabel3 = new javax.swing.JLabel();
        GregSectionLabel4 = new javax.swing.JLabel();
        KarawanSectionLabel3 = new javax.swing.JLabel();
        HelpLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        HomePagePanel.setBackground(new java.awt.Color(51, 204, 255));

        ShoaibLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoaibLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salary.png"))); // NOI18N
        ShoaibLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShoaibLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShoaibLogoLabelMouseClicked(evt);
            }
        });

        KarawanLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KarawanLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/graduate.png"))); // NOI18N
        KarawanLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KarawanLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KarawanLogoLabelMouseClicked(evt);
            }
        });

        GregLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GregLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school-bag.png"))); // NOI18N
        GregLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GregLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GregLogoLabelMouseClicked(evt);
            }
        });

        KarawanNameLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        KarawanNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        KarawanNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KarawanNameLabel.setText("Karawan Azizi - ");

        WelcomeIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/welcome.png"))); // NOI18N

        GregNameLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        GregNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        GregNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GregNameLabel.setText("Gregory Mitchell ;");

        ShoaibNameLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        ShoaibNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ShoaibNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoaibNameLabel.setText("Shoaib Mohammad ;");

        ShoaibSectionLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        ShoaibSectionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ShoaibSectionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoaibSectionLabel1.setText("Learn about helping hands !");

        KarawanSectionLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        KarawanSectionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        KarawanSectionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KarawanSectionLabel1.setText("Manage and stay on top of your student information!");

        KarawanSectionLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        KarawanSectionLabel2.setForeground(new java.awt.Color(255, 255, 255));
        KarawanSectionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KarawanSectionLabel2.setText("Keep up-to-date with upcoming activities!");

        ShoaibSectionLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        ShoaibSectionLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ShoaibSectionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoaibSectionLabel2.setText("Learn about financial aids,");

        ShoaibSectionLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        ShoaibSectionLabel3.setForeground(new java.awt.Color(255, 255, 255));
        ShoaibSectionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShoaibSectionLabel3.setText("such as grants and sponsorships !");

        GregSectionLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        GregSectionLabel2.setForeground(new java.awt.Color(255, 255, 255));
        GregSectionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GregSectionLabel2.setText("Keep on top of and store recources");

        GregSectionLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        GregSectionLabel3.setForeground(new java.awt.Color(255, 255, 255));
        GregSectionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GregSectionLabel3.setText("A contact form to get in touch with someone on our team!");

        GregSectionLabel4.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        GregSectionLabel4.setForeground(new java.awt.Color(255, 255, 255));
        GregSectionLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GregSectionLabel4.setText("A report generator !");

        KarawanSectionLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        KarawanSectionLabel3.setForeground(new java.awt.Color(255, 255, 255));
        KarawanSectionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KarawanSectionLabel3.setText("Calculate your gpa to ensur e you meet the requiremtns !");

        HelpLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        HelpLabel.setForeground(new java.awt.Color(255, 255, 255));
        HelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelpLabel.setText("Please choose were you would like to go by clicking on the icon!");

        javax.swing.GroupLayout HomePagePanelLayout = new javax.swing.GroupLayout(HomePagePanel);
        HomePagePanel.setLayout(HomePagePanelLayout);
        HomePagePanelLayout.setHorizontalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(WelcomeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HomePagePanelLayout.createSequentialGroup()
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(KarawanLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(ShoaibLogoLabel))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(KarawanNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(ShoaibNameLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addComponent(KarawanSectionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addComponent(KarawanSectionLabel2)
                                .addGap(55, 55, 55))
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addComponent(KarawanSectionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePagePanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(ShoaibSectionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ShoaibSectionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShoaibSectionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GregSectionLabel3)
                            .addComponent(GregSectionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(GregLogoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GregNameLabel)
                            .addComponent(GregSectionLabel2))
                        .addGap(85, 85, 85))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HelpLabel)
                .addGap(103, 103, 103))
        );
        HomePagePanelLayout.setVerticalGroup(
            HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addComponent(KarawanLogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KarawanNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KarawanSectionLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KarawanSectionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(HomePagePanelLayout.createSequentialGroup()
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePagePanelLayout.createSequentialGroup()
                                .addComponent(ShoaibLogoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ShoaibNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GregNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(GregLogoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShoaibSectionLabel1)
                            .addComponent(GregSectionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShoaibSectionLabel2)
                            .addComponent(GregSectionLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShoaibSectionLabel3)
                            .addComponent(KarawanSectionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GregSectionLabel4))))
                .addGap(33, 33, 33)
                .addComponent(HelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KarawanLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KarawanLogoLabelMouseClicked
        JOptionPane.showMessageDialog(null, "This is only the individual version, please see the group version for a more complete view");
    }//GEN-LAST:event_KarawanLogoLabelMouseClicked

    private void GregLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GregLogoLabelMouseClicked
        new EducationalEnviormentGUIGregory().setVisible(true);//create Gregory's GUI if Gregs logo label is mouse clickded
        dispose(); // rid of current frame using dispose
    }//GEN-LAST:event_GregLogoLabelMouseClicked

    private void ShoaibLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShoaibLogoLabelMouseClicked
         JOptionPane.showMessageDialog(null, "This is only the individual version, please see the group version for a more complete view");
    }//GEN-LAST:event_ShoaibLogoLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GregLogoLabel;
    private javax.swing.JLabel GregNameLabel;
    private javax.swing.JLabel GregSectionLabel2;
    private javax.swing.JLabel GregSectionLabel3;
    private javax.swing.JLabel GregSectionLabel4;
    private javax.swing.JLabel HelpLabel;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel KarawanLogoLabel;
    private javax.swing.JLabel KarawanNameLabel;
    private javax.swing.JLabel KarawanSectionLabel1;
    private javax.swing.JLabel KarawanSectionLabel2;
    private javax.swing.JLabel KarawanSectionLabel3;
    private javax.swing.JLabel ShoaibLogoLabel;
    private javax.swing.JLabel ShoaibNameLabel;
    private javax.swing.JLabel ShoaibSectionLabel1;
    private javax.swing.JLabel ShoaibSectionLabel2;
    private javax.swing.JLabel ShoaibSectionLabel3;
    private javax.swing.JLabel WelcomeIconLabel;
    // End of variables declaration//GEN-END:variables
}
